Models/Date.cs
using System.ComponentModel.DataAnnotations;

namespace VisitList.Models;

public class Date
{
    [Range(1, 31)]
    public int day { get; set; }

    [Range(1, 12)]
    public int month { get; set; }

    [Range(1900, 2100)]
    public int year { get; set; }

    public override string ToString()
    {
        string dayToDisplay = day < 10 ? "0" + day : day.ToString();
        string monthToDisplay = month < 10 ? "0" + month : month.ToString();
        return dayToDisplay + "/" + monthToDisplay + "/" + year;
    }

    public string toInputDisplay()
    {
        string dayToDisplay = day < 10 ? "0" + day : day.ToString();
        string monthToDisplay = month < 10 ? "0" + month : month.ToString();
        return  year + "-" + monthToDisplay + "-" + dayToDisplay;
    }

    public static bool isValid(string date)
    {
        var splittedDate = date.Split("-");
        return date.Split("-").Count() == 3 && splittedDate[0].Count() == 4 && splittedDate[1].Count() == 2 && splittedDate[2].Count() == 2;
    }

    public static int getYearFromForm(string date)
    {
        return int.Parse(date.Split("-")[0]);
    }

    public static int getMonthFromForm(string date)
    {
        return int.Parse(date.Split("-")[1]);
    }

    public static int getDayFromForm(string date)
    {
        return int.Parse(date.Split("-")[2]);
    }
}

Models/Visit.cs
using System.ComponentModel.DataAnnotations;

namespace VisitList.Models;

public class Visit
{
    public int Id { get; set; }

    [Required]
    public string? Name { get; set; }

    public Date? StartDate {get; set;}
    public Date? EndDate {get; set;}

    public string? Comment {get; set;}

    public List<string> PhotoList {get; set;} = new();

    public string getStartDateDisplay()
    {
        return StartDate != null ? StartDate.toInputDisplay() : "";
    }

    public string getEndDateDisplay()
    {
        return EndDate != null ? EndDate.toInputDisplay() : "";
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VisitList.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VisitList.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/ModifyVisit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VisitList.Models;
using VisitList.Services;

namespace Visits.Pages
{
    public class ModifyVisitModel : PageModel
    {
        public Visit visit = new();

        public void OnGet()
        {
            int id = int.Parse(HttpContext.Request.Query["visitId"]);
            Visit? temp = VisitService.Get(id);
            if(temp != null)
            {
                visit = temp;
            }
        }

        public IActionResult OnPostModifyVisit(int id)
        {
            Visit? visit = VisitService.Get(id);
            if(visit == null)
            {
                return Page();
            }

            return RedirectToAction("Get");
        }

        public IActionResult OnPostUpdate()
        {
            Visit visit = new();
            visit.Id = int.Parse(Request.Form["Id"]);
            visit.Name = Request.Form["Name"];
            
            if(Date.isValid(Request.Form["StartDate"]))
            {
                if(visit.StartDate == null)
                {
                    visit.StartDate = new();
                }
                
                visit.StartDate.year = Date.getYearFromForm(Request.Form["StartDate"]);
                visit.StartDate.month = Date.getMonthFromForm(Request.Form["StartDate"]);
                visit.StartDate.day = Date.getDayFromForm(Request.Form["StartDate"]);
            }

            if(Date.isValid(Request.Form["EndDate"]))
            {
                if(visit.EndDate == null)
                {
                    visit.EndDate = new();
                }
                visit.EndDate.year = Date.getYearFromForm(Request.Form["EndDate"]);
                visit.EndDate.month = Date.getMonthFromForm(Request.Form["EndDate"]);
                visit.EndDate.day = Date.getDayFromForm(Request.Form["EndDate"]);
            }

            visit.Comment = Request.Form["Comment"];
            VisitService.Update(visit);
            return Redirect("/Visits");
        }

         public IActionResult OnGetDeletePhoto(int visitId, string photo)
        {
            VisitService.DeletePhoto(visitId, photo);
            return RedirectToAction("Get", new { visitId = visitId });
        }

        public IFormFile? UploadPhoto { get; set; }

        public IActionResult OnPostAddPhoto(int visitId)
        {
            Visit? visitToAdd = VisitService.Get(visitId);
            if(visitToAdd != null && UploadPhoto != null)
            {
                int id = 0;
                foreach(var photo in visitToAdd.PhotoList)
                {
                    id = int.Parse(photo.Split("__")[1].Split(".")[0]);
                }
                ++id;
                var fileName = visitToAdd.Name + "__" + id + System.IO.Path.GetExtension(UploadPhoto.FileName);
                var file = Path.Combine("wwwRoot\\Photos", fileName);
                using (var fileStream = new FileStream(file, FileMode.Create))
                {
                    UploadPhoto.CopyTo(fileStream);
                }

                VisitService.AddPhoto(int.Parse(Request.Form["Id"]), fileName);
            }
            return RedirectToAction("Get", new { visitId = Request.Form["Id"] });
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VisitList.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/Visits.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VisitList.Models;
using VisitList.Services;

namespace Visits.Pages
{
    public class VisitsModel : PageModel
    {
         public List<Visit> visitList = new();
        public void OnGet()
        {
            visitList = VisitService.GetAll();
        }

        public string StartDateText(Visit visit)
        {
            if(visit.StartDate == null)
            {
                return "";
            }
            return visit.StartDate.ToString();
        }

        public string EndDateText(Visit visit)
        {
            if(visit.EndDate == null)
            {
                return "";
            }
            return visit.EndDate.ToString();
        }

        public IActionResult OnPostDelete(int id)
        {
            VisitService.Delete(id);
            return RedirectToAction("Get");
        }

        public IActionResult OnPostUpdate(Visit visit)
        {
            return RedirectToPage("/ModifyVisit", new { visitId = visit.Id });
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/ModifyVisit.cshtml
@page
@model Visits.Pages.ModifyVisitModel
@{
}

<h1>Modify your Visit</h1>

<a>@Model.visit.Name</a>
<a>@Model.visit.StartDate</a>
<a>@Model.visit.EndDate</a>

<form id="modifyForm" method="post" asp-page-handler="Update" asp-route-id="@Model.visit">
    <table>
        <tr>
            <td>
                <a>Name :</a>
            </td>
            <td>
                <input name="Name" value="@Model.visit.Name">
            </td>
        </tr>
        <tr>
            <td>
                <a>Start date :</a>
            </td>
            <td>
                <input name="StartDate" value=@Model.visit.getStartDateDisplay() type="date">
            </td>
        </tr>
        <tr>
            <td>
                <a>End Date :</a>
            </td>
            <td>
                <input name="EndDate" value=@Model.visit.getEndDateDisplay() type="date">
            </td>
        </tr>
        <tr>
            <td>
                <a>Comment :</a>
            </td>
            <td>
                <input name="Comment" value="@Model.visit.Comment" type="text">
            </td>
        </tr>
    </table>
    <input name="Id" value=@Model.visit.Id type="hidden">
    <button class="btn btn-danger" form="modifyForm">Modify</button>
</form>
<table>
    @foreach (var photo in Model.visit.PhotoList)
    {
        <tr>
            <td>
                <a>Photo n°@(Model.visit.PhotoList.IndexOf(@photo)+1) :</a>
            </td>
            <td>
                <img src="/Photos/@photo" alt="Photo n° @Model.visit.PhotoList.IndexOf(@photo)" style="height: 300px;">
            </td>
            <td>
                <a asp-page="ModifyVisit" asp-page-handler="DeletePhoto" asp-route-visitId=@Model.visit.Id asp-route-photo=@photo>Delete</a>
            </td>
        </tr>
    }
</table>
<form method="post" enctype="multipart/form-data" asp-page-handler="AddPhoto" asp-route-visitId=@Model.visit.Id>
    <input type="file" asp-for="UploadPhoto"/>
    <input type="hidden" value=@Model.visit.Id name="Id"/>
    <input type="submit"/>
</form>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VisitList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VisitList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">VisitList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Visits">Visit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - VisitList - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/Visits.cshtml
@page
@using VisitList.Models
@model Visits.Pages.VisitsModel
@{
     ViewData["Title"] = "Visit List";
}

<h1>Visit List</h1>

<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Comment</th>
            <th scope="col">Modify</th>
            <th scope="col">Delete</th>
            <th scope="col">Photo</th>
        </tr>
    </thead>
    @foreach (var visit in Model.visitList)
    {
        <tr style="vertical-align: middle;">
            <td>@visit.Name</td>
            <td>@Model.StartDateText(visit)</td>
            <td>@Model.EndDateText(visit)</td>
            <td>@visit.Comment</td>
            <td>
                <form method="post" asp-page-handler="Update" asp-route-id="@visit.Id">
                    <button class="btn btn-danger">Modify</button>
                </form>
            </td>
            <td>
                <form method="post" asp-page-handler="Delete" asp-route-id="@visit.Id">
                    <button class="btn btn-danger">Delete</button>
                </form>
            </td>
            <td>
                @if(@visit.PhotoList.Count() > 0){
                    <img src="/Photos/@visit.PhotoList[0]" alt="Image" style="height: 150px; border-radius: 25%;">
                }
            </td>
        </tr>
    }
</table>